// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareTestOgSikkerhed.Models;

#nullable disable

namespace SoftwareTestOgSikkerhed.Migrations
{
    [DbContext(typeof(Dbcontext))]
    [Migration("20240923114404_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoftwareTestOgSikkerhed.Models.Cpr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CprId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cprs");
                });

            modelBuilder.Entity("SoftwareTestOgSikkerhed.Models.Todolist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CprId")
                        .HasColumnType("int");

                    b.Property<string>("TodoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TodoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CprId");

                    b.ToTable("Todolist");
                });

            modelBuilder.Entity("SoftwareTestOgSikkerhed.Models.Todolist", b =>
                {
                    b.HasOne("SoftwareTestOgSikkerhed.Models.Cpr", null)
                        .WithMany("Todolist")
                        .HasForeignKey("CprId");
                });

            modelBuilder.Entity("SoftwareTestOgSikkerhed.Models.Cpr", b =>
                {
                    b.Navigation("Todolist");
                });
#pragma warning restore 612, 618
        }
    }
}
